README.md
addon/models.js
addon/models/construction-project.js
addon/models/search-result.js
addon/models/xml-model.js
addon/services/construction-project.js
addon/templates/project/index.hbs
package.json
yarn.lock

Some XML elements can appear multiple times in the DOM, e.g. realestateIdentification can be part of a constructionProject or of a building. By specifying the root (direct parent) we don't accidentally query properties of children.
Depends on #10

fix(model): specify "root" object for selectors

---

addon/components/project-form/field.hbs
addon/components/project-form/field.js
addon/components/project-form/input.js
addon/components/project-form/select.js
addon/components/project-form/textarea.js
addon/templates/project/form.hbs

The `{{eq @value currentOption}}` would break if `@value` is a string since `eq` works by strict comparison.
Now you can specify a optional argument which then converts the value to the specified type.
Also remove unneeded component files since the update method for those components is handled in `project-form/field.js`.

fix(select): convert the values to number for selects since otherwise the active option is broken

---

addon/services/auth-fetch.js

The properties `username` and `password` can now be set again in the passed config service.
This is needed as long as we dont have access to the current `municipalityId` and
`constructionSurveyDepNumber` for the logged in user from the gwr API.

fix(auth): reenable configuration for user and password in the config service

---

addon/controllers/application.js
addon/routes/application.js
addon/templates/application.hbs
tests/unit/controllers/application-test.js
tests/unit/routes/application-test.js

Make login modal invisible after successful login to ensure
that the underlying ui is interactable.
Related to: #62

fix(login): hide login modal after authentication

---

addon/components/link-building-modal.hbs
addon/components/login-modal.hbs
addon/modifiers/toggle-modal.js
app/styles/ember-ebau-gwr.scss
package.json
yarn.lock

Fix focus-trap issues with modal visibility and contain
application modal container and its contents to gwr
application.
Note: Necessitates adding `@import "ember-ebau-gwr";` to `camac-ng/ember-camac-ng/app/styles/app.scss` for changes to take effect.
Link building:  
Login:

fix(modal): show and contain gwr modal

---

README.md
app/styles/ember-ebau-gwr.scss

The full uikit import should always be in the host app, otherwise uikit
will be added multiple times to the compiled css.

fix: don't import full uikit

---

addon/components/model-form/date.hbs
addon/components/model-form/date.js

Fix date input bug where the input can no longer be picked
after manually entering a value in the input field.
Resolves #98

fix(model-form): fix resetting date input after manual entry

---

addon/components/model-form/header/errors.hbs

Make error alert message in header appear less critical.

style(header): change error alert in header to warning

---

addon/templates/project/form.hbs

Allow any integer value within the min/max requirements to
be entered in the totalCostsOfProject field. The backend
accepts the value and rounds it to the nearest 1000.
Resolves #100

fix(project): allow unrounded values for totalCostsOfProject field

---

addon/templates/project/form.hbs
addon/validations/construction-project.js

Backend requires the typeOfConstruction field to be set on
a project. The field's presence is checked through the
corresponding model-form validation.
Resolves #101

fix(project): make typeOfConstruction field of project required

---

addon/components/model-form/header/status-selector/submit-parameters.hbs
addon/controllers/building/edit/dwelling/edit.js
addon/controllers/building/edit/entrance/edit/index.js
addon/controllers/building/edit/form.js
addon/controllers/project/form.js
addon/models/construction-project.js
addon/templates/project/form.hbs
addon/validations/construction-project.js
addon/validations/status/status-project-change.js
translations/construction-project/de.yaml

Ensure further dates can be entered when modifying a project.
When creating a project, only the announcement and building permit
date are allowed, all other date fields are hidden.
Add duration of construction phase field to project
modification form.
**Modify project**  
**Create project**  
Relates to #99

fix(project): fix date fields in project form

---

addon/components/linked-models.hbs
addon/components/linked-projects.hbs
addon/templates/project.hbs
app/styles/ember-ebau-gwr.scss

This change mainly helps to differentiate the project list from the linked building list.
@luytena Would be awesome to have some thought from you about this design implementation!

feat(linked-projects): add a visual separation to projects list

---

addon/xml/templates/dwelling.js

- fix(project-nav-tab): check for superstructure id not infrastructure
- fix(dwelling): use correct field for dateOfDemolition

fix dateOfDemolition

---

addon/services/construction-project.js

Only checks for linked buildings and dwellings if the project
type is a superstructure (Hochbau). Ignores work without
attached buildings.

fix(life-cycles): prohibit checks for infrastructure projects

---

addon/components/link-building-modal.hbs
addon/components/link-building-modal.js
addon/templates/project/form.hbs
tests/dummy/app/services/gwr-config.js
tests/dummy/app/templates/application.hbs

Ensure the confirmation dialog modal when changing the type of
the construction project (superstructure/infrastructure) is
added to the correct modal container.

fix(project): correct confirmation dialog modal container

---

addon/models/construction-project.js
addon/templates/project/form.hbs
addon/validations/status/status-project-change.js
addon/validations/status/status-project-correction.js
addon/xml/templates/construction-project.js
translations/construction-project/de.yaml

The API returns the cancellation date instead of the non-
realisation date. All references to that field are updated
accordingly.

fix(project): replace non-realisation date with cancellation date

---

addon/controllers/building/edit/entrances.js
addon/models/building-entrance.js
addon/services/building-entrance.js
addon/services/gwr.js
addon/templates/building/edit/entrances.hbs
translations/building/de.yaml

Trigger a request for building entrance deactivation if at least
one building entrance is attached to the building. Show appropriate
error message if API request fails due to active dwellings
attached to the building entrance.

feat(building): enable building entrance deactivation

---

addon/routes/project/new.js

Since we moved the fetchProject call from the {{did-insert}} to the setupController
we need to extend the new route from the edit route.

fix(project/new): extend new route from form route

---

addon/components/model-form/header/status-selector.hbs
addon/components/model-form/header/status-selector/submit-parameters.hbs
addon/components/model-form/submit-errors.hbs
addon/controllers/building/edit/dwelling/edit.js
addon/controllers/building/edit/form.js
addon/controllers/project/form.js
addon/services/gwr.js
tests/dummy/app/services/gwr-config.js
translations/de.yaml

Prepend the current url base path to the error links to ensure
that links direct to the correct location when gwr is mounted
as an engine.

fix(life-cycles): correct life cycle error links for camac-ng

---

.github/workflows/release.yml

ember-validated-form dropped node v10 support

ci(release): set node version to v14

---

addon/components/model-errors.hbs
addon/components/model-errors/error-indicator.hbs
addon/components/model-errors/header.hbs
addon/templates/project/errors.hbs
app/styles/ember-ebau-gwr.scss

For issue lists, the model id is now fixed width to avoid
confusing indentation between buildings depending on
length of id.

refactor(issues): use fixed width for model ids in issue lists

---

addon/components/back-route.hbs
addon/components/sub-nav.hbs
addon/templates/search-building.hbs
addon/templates/search-project.hbs

Enable the user to return to the previous route after
entering the project search or building search route.

feat(search): add back routes for building and project search

---

addon/components/model-form/header/actions.hbs
addon/components/model-form/header/actions.js
addon/controllers/import.js
addon/services/import-state.js
app/styles/ember-ebau-gwr.scss
tests/unit/services/import-state-test.js
translations/de.yaml

Ensure that failed data imports are handled and don't
cause the entire application to malfunction. The import
button for the object is disabled with a tooltip in case
the import fails.

fix(import): add error handling for failed data imports

---

addon/controllers/building/edit/entrance/edit/link-street.js
addon/controllers/search-building.js
addon/routes/building/edit/entrance/new.js
addon/services/street.js

Update the language option extraction for street names to allow
country codes in the locale (e.g. de-ch) provided through the host
application's intl service.

fix(street): enable country-coded locales for street language options

---

addon/services/building-entrance.js
addon/services/building.js
translations/building-entrance/de.yaml
translations/building-entrance/fr.yaml
translations/building/de.yaml
translations/building/fr.yaml

Improve the locality error messages that are triggered
when the GWR-API returns a "No link between locality and street"
error during building or entrance creation.

fix(intl): improve locality error messages

---

addon/components/link-street.hbs
addon/components/model-form.hbs
addon/components/model-form/header.hbs
addon/components/model-form/header/actions.hbs
addon/components/quarterly-closure/disabled-form-info.hbs
addon/controllers/building/edit/dwelling/edit.js
addon/controllers/building/edit/entrance/edit/index.js
addon/controllers/building/edit/form.js
addon/controllers/project/form.js
addon/services/quarterly-closure.js
addon/templates/building/edit/dwelling/edit.hbs
addon/templates/building/edit/entrance/edit/index.hbs
addon/templates/building/edit/form.hbs
addon/templates/project/form.hbs
translations/quarterly-closure/de.yaml

qc disable form

---

README.md

BREAKING CHANGE: Drop node v12 support.

docs(readme): update supported node version

---

addon/components/model-form/header.hbs
addon/components/model-form/header/actions.hbs
addon/controllers/project.js
addon/services/construction-project.js
addon/templates/project/form.hbs
translations/de.yaml

Ignore archived or deactivated construction projects, that are still referenced through an instance link, but can no longer be retrieved through the API. In addition, improve the header layout such that element wrapping is applied properly when little space is available.

fix(projects): ignore linked archived projects & improve header layout

---

addon/components/project-nav.hbs

Remove disabling of linked buildings tab to allow users to unlink buildings when switching from superstructure projects to infrastructure projects.

fix(buildings): never disable linked building tab

---

addon/components/search-street.hbs
addon/components/search-street.js
addon/templates/building/edit/entrance/edit/index.hbs
addon/templates/building/edit/form.hbs
app/styles/ember-ebau-gwr.scss
tests/integration/components/search-street-test.js
translations/de.yaml
translations/fr.yaml

This will resolve the required connection between locality and street for creating new buildings/entrances.
- create new building
- create new entrance
Disabled state
Enabled
Search
Selected

feat(street-search): replace linkStreet sub-form with street select

---

tests/dummy/app/controllers/application.js

In case one accidentally closes the initial prompt asking for the canton, there is no way back (besides clearing localStorage) to receive that prompt again. This took me some time to realize while onboarding. Just to prevent future devs to experience the same I would suggest this small fix.
After the first prompt the localStorage key `canton` will resolve to `null`. This get's somehow transformed into a string `"null"` which will not fall into the `if (!canton)` trap and prevent further prompts for the current canton. This halts the application as it runs into an error.

fix: initial setup of canton to local storage

---

addon/controllers/project.js

Instance-links don't correctly redirect to the relevant project. Handling null accesses currently leads to display issues in the navigation and need to be properly addressed and fixed.

fix(project): revert handling of missing current route information

---

addon/components/model-form.hbs
addon/components/model-form/field.hbs
addon/components/search-street.hbs
addon/components/search-street.js
addon/controllers/building/edit/entrance/edit/index.js
addon/controllers/building/edit/form.js
addon/templates/building/edit/entrance/edit/index.hbs
addon/templates/building/edit/form.hbs
addon/validations/building-entrance.js
addon/xml/templates/street.js
app/styles/_validated-form.scss
app/styles/ember-ebau-gwr.scss
tests/integration/components/search-street-test.js
translations/de.yaml
translations/fr.yaml

First part of implementing #738 
**Building creation**
**Street validation**

feat: improve streeet search component

---

addon/models/options.js
addon/services/languages.js
addon/services/street.js
tests/unit/services/languages-test.js

Needs #741 
Second part of https://github.com/inosca/ember-ebau-gwr/issues/738
**Multilingual street search**
Update after short discussion with @czosel:
We want to stay very defensive with caching and fire one or two requests more rather then getting trapped in some request cache shenanigans. Opting for only canton relevant languages will most effectively cut down request count.

feat: improve streeet search api
