inosca/ember-ebau-gwr

README.md, addon/models.js, addon/models/construction-project.js, addon/models/construction-projects-list.js, addon/models/search-result.js, addon/models/xml-model.js, addon/services/construction-project.js, addon/templates/project/index.hbs, addon/templates/search-project.hbs, config/ember-try.js, package.json, translations/de.yaml, yarn.lock
=> feat: search by eproid

.gitignore, README.md, addon/controllers/project/index.js, addon/engine.js, addon/models.js, addon/models/construction-project.js, addon/models/construction-projects-list.js, addon/models/search-result.js, addon/models/xml-model.js, addon/services/construction-project.js, addon/templates/project/index.hbs, addon/templates/search-project.hbs, config/ember-try.js, package.json, tests/dummy/app/app.js, tests/dummy/app/services/gwr-config.js, translations/de.yaml, yarn.lock
=> Data import

addon/models/address.js, addon/models/client.js, addon/models/construction-project.js, addon/models/options.js, addon/models/realestate-identification.js, addon/templates/project/form.hbs, translations/de.yaml
=> Adapt to new GWR API changes

addon/models/building-entrance.js, addon/models/building.js, addon/models/buildings-list.js, addon/models/construction-project.js, addon/models/date-of-construction.js, addon/models/street.js, addon/models/xml-model.js
**The class names get minified and so the selector returns nothing.**
=> fix(models): dont take class name as querySelector root for xml

tests/dummy/app/templates/application.hbs
Enhance dummy application with surrounding container
and padding.
=> style(dummy): add container and padding to dummy app

addon/components/linked-models.hbs, addon/templates/project.hbs, translations/de.yaml
Add translations of the pluralized model names and
apply usage in templates.
=> fix(intl): correct pluralization of model translations

addon/components/model-form.hbs, addon/components/model-form.js, addon/components/model-form/date.hbs, addon/components/model-form/diff.hbs, addon/components/model-form/diff.js, addon/components/model-form/field.hbs, addon/components/model-form/field.js, addon/components/model-form/step.hbs, addon/components/model-form/submit.hbs, addon/controllers/project/form.js, addon/models/building-work.js, addon/models/building.js, addon/models/construction-project.js, addon/templates/building/form.hbs, addon/templates/project/form.hbs, addon/validations/building.js, addon/validations/project.js, addon/validators/presence-nested.js, config/environment.js, package.json, tests/dummy/app/styles/_validated-form.scss, tests/dummy/app/styles/app.scss, tests/dummy/config/environment.js, translations/de.yaml, yarn.lock
Replace existing forms, input fields and their validations
with an implementation using ember-validated-form
and ember-changeset.
=> refactor(form): use ember-validated-form for forms

app/styles/_validated-form.scss, app/styles/ember-ebau-gwr.scss, tests/dummy/app/styles/app.scss
Ensure the ember-validated-form style files are importable
by other applications via ember-ebau-gwr.
=> fix(style): change location of validated-form style files

addon/components/model-form.hbs, addon/controllers/project/linked-buildings.js, addon/models/building-work.js, addon/models/construction-project.js, addon/models/coordinates.js, addon/routes/building/new.js, addon/templates/project/form.hbs, addon/validations/dwelling.js, addon/xml/templates/building.js
=> minor fixes

addon/components/login-modal.hbs, addon/components/logout.hbs, addon/components/logout.js, addon/services/auth-fetch.js, addon/templates/application.hbs, app/styles/ember-ebau-gwr.scss, tests/dummy/mirage/config.js, translations/de.yaml
Enable the user to terminate the authenticated
session and return to the login modal.
Depends on: [ebau-gwr PR](https://github.com/adfinis-sygroup/ebau-gwr/pull/23)
=> feat(logout): enable logout functionality

addon/components/model-form/header/actions.hbs
Inspired by https://getuikit.com/docs/button#button-group-with-dropdowns
=> fix(model-form/header): improve ui of context menu button

addon/engine.js, addon/services/auth-fetch.js, tests/dummy/app/app.js, tests/dummy/app/services/session.js, tests/helpers/session-stub.js, tests/unit/services/auth-fetch-test.js
Fetch refreshed authentication token from the session
service supplied through the application embedding the
the GWR engine. Applies to login and logout requests.
=> fix(auth): ensure authentication token is refreshed

addon/controllers/building/edit/form.js, addon/models/construction-project.js, addon/services/building.js, addon/templates/building/edit/form.hbs, addon/xml/templates/building.js
Allow buildings to be created with any initial status. Depending
on the selected status, different API requests are emitted.
=> fix(building): allow all states to be set for new buildings

addon/components/link-building-modal.js, addon/controllers/building/edit/form.js, addon/models/building-entrance.js, addon/models/construction-project.js, addon/models/dwelling.js, addon/routes/building/edit/dwelling/new.js, addon/routes/building/new.js, addon/services/building.js, addon/templates/building/edit/dwelling/edit.hbs, addon/templates/building/edit/entrance/edit/index.hbs, addon/templates/building/edit/form.hbs, addon/templates/project/form.hbs, addon/xml/templates/building.js, translations/building/de.yaml
- fix(dwelling;building): remove status select
- fix(building-entrance): display coordinates and ARBID
- fix(dwelling): make residence flags readonly
- fix(form): display plain text with form-labels instead of bold-text
=> streamline state

addon/templates/project.hbs, app/styles/ember-ebau-gwr.scss
- feat(project-nav): display building tab on infra projects
- refactor(project-nav): add padding to table
=> refactor(project-nav): add padding to table

addon/models/client.js, addon/models/construction-project.js, addon/models/identification.js
Ensure correct person or organisation identification is read
or written depending on the selected client type.
=> fix(project): fix client identification template

addon/components/linked-models.hbs, addon/components/linked-models.js, addon/components/linked-projects.hbs, addon/components/linked-projects.js, addon/controllers/project.js, addon/templates/project.hbs
Render tooltips in correct application container. Fixes
integration issue with camac-ng.
=> fix(ui): render tooltips in correct application container

addon/components/model-form/header/actions.hbs, addon/controllers/project/form.js, addon/helpers/show-model-field.js, addon/templates/building/edit/dwelling/edit.hbs, addon/templates/building/edit/form.hbs, addon/templates/project/form.hbs, translations/construction-project/de.yaml
Ensure that model form fields that are only shown under
certain circumstances are shown during import if the
field in question has importable data.
=> fix(import): show conditional fields during import

config/ember-try.js, translations/building-entrance/fr.yaml, translations/building/de.yaml, translations/building/fr.yaml, translations/construction-project/fr.yaml, translations/dwelling/de.yaml, translations/dwelling/fr.yaml, translations/fr.yaml, translations/locality/fr.yaml, translations/street/fr.yaml
Add all French intl translation files to match the existing
German intl translation files.
=> feat(translations): include French translation files

addon/components/housing-stat-link.hbs, addon/components/project-nav.hbs, addon/components/quarterly-closure/error-list/survey-department-errors.hbs, addon/components/quarterly-closure/error-list/survey-department-errors.js, translations/quarterly-closure/de.yaml
- feat(global): add landing page
- feat(quarterly-closure): add fist closure status handling
- feat(quarterly-closure): add error list to quarterly closure
- feat(quarterly-closure): add link to housing stat for maintenance cost
=> qc housing stat link

addon/components/model-form/submit.hbs, addon/components/search/filters.hbs, addon/templates/building/edit/entrance/edit/link-street.hbs, addon/templates/search-building.hbs, addon/templates/search-project.hbs, app/styles/ember-ebau-gwr.scss
fix: incorrect search btn labels
=> fix: incorrect search btn labels

addon/components/import-modal.hbs, addon/components/model-form.hbs, addon/components/model-form.js, addon/components/model-form/field.js, addon/components/model-form/header/actions.hbs, addon/components/model-form/header/actions.js, addon/controllers/import.js, addon/resources/import.js, addon/templates/building/edit/dwelling/edit.hbs, addon/templates/building/edit/entrance/edit/index.hbs, addon/templates/building/edit/form.hbs, addon/templates/project/form.hbs
The get is needed since `this.args.attr` could also be a property path for example `building.description`.
=> fix(building/import): revert a refactor from 4894e52

README.md, addon/components/search.js
=> fix: pagination

addon/components/search.hbs, addon/components/search/filters.hbs, addon/components/search/filters.js, addon/templates/search-building.hbs, addon/templates/search-project.hbs, tests/integration/components/search/filters-test.js
- style(search): move extended search button next to submit search button
=> fix search layout

addon/components/search/filters.hbs, addon/templates/search-building.hbs, addon/templates/search-project.hbs, package.json, yarn.lock
- fix(search): make prompt selectable
=> qc update validated form

addon/components/quarterly-closure/title.hbs, addon/helpers/current-quarter.js, addon/templates/global-landing-page.hbs, tests/integration/helpers/current-quarter-test.js
- fix(quarterly-closure): display quarter according to bfs
=> display correct quarter

addon/services/auth-fetch.js
- fix(login): prevent requests if no token is returned from gwr api
=> fix requests with no token

.github/dependabot.yml, package.json, yarn.lock
Avoid build error introduced when upgrading to
ember-engines v0.9.0 (ember-engines/ember-engines#833).
=> chore(deps): downgrade ember-engines

addon/components/login-modal.hbs, translations/de.yaml, translations/fr.yaml
=> feat(login): add a contact to the login site in case it doesn't work

.eslintrc.js, .github/dependabot.yml, .github/workflows/release.yml, .github/workflows/test.yml, .npmignore, .prettierrc.js, .stylelintignore, .stylelintrc.js, README.md, addon/controllers/building/edit/entrance/edit/link-street.js, app/styles/ember-ebau-gwr.scss, index.js, package.json, tests/dummy/config/ember-cli-update.json, tests/dummy/mirage/config.js, yarn.lock
BREAKING CHANGE: Drop support for Ember v3.
=> chore(deps): update dependencies

addon/components/model-form.hbs, addon/components/model-form/field.hbs, addon/components/search-street.hbs, addon/components/search-street.js, addon/controllers/building/edit/entrance/edit/link-street.js, addon/templates/building/edit/entrance/edit/index.hbs, addon/templates/building/edit/form.hbs, addon/validations/building-entrance.js
* fix(street-search): correct validation rules, which lead to silent failure of submitting/changing entrance streets
* fix(link-street): sync linked locality after street selection on `link-street` view
=> fix: street-search and link-street
